FROM ubuntu:22.04

RUN apt-get update && \
    apt-get install -y curl git build-essential && \
    rm -rf /var/lib/apt/lists/*

RUN curl -L https://foundry.paradigm.xyz | bash
ENV PATH="/root/.foundry/bin:${PATH}"
RUN foundryup

EXPOSE 8545

CMD ["anvil", "--host", "0.0.0.0", "--port", "8545"]
