version: '3.8'

services:
  anvil:
    build:
      context: .
      dockerfile: Dockerfile.anvil
    container_name: esport-oracle-anvil
    ports:
      - "8545:8545"
    networks:
      - esport-network
    healthcheck:
      test: ["CMD", "curl", "-X", "POST", "-H", "Content-Type: application/json", "--data", '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}', "http://localhost:8545"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  deployer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esport-oracle-deployer
    depends_on:
      anvil:
        condition: service_healthy
    networks:
      - esport-network
    environment:
      - RPC_URL=http://anvil:8545
      - PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80

networks:
  esport-network:
    driver: bridge
